void delay(int);
void limpaTela(void);
int Digito(char);
int letra(char);
int validarNome(char*);
int caracteresEmail(char);
int validarEmail(char*);
int validarCelular(char*);
int Bissexto(int);
int Data(int, int, int);
int validarData(char*);
int validarNasc(char*);
int validarID(char*);
int validarCargo(char*);
int validarHorario(char*);
int validarPreco(const char*);
int validarQuantidade(int);
